[tools]
terraform = "1.6.6"
kubectl = "1.29.2"
helm = "3.14.2"
awscli = "2.15.10"
k9s = "0.32.4"
node = "20"
python = "3.12"
go = "1.22"
flux2 = "2.4.0"
argocd = "2.12.5"
istioctl = "1.28.4"
neovim = "0.11.5"
